
apiVersion: v1
kind: Service
metadata:
  name: devops-03-pipeline-aws-service
  labels: 
    app: devops-03-pipeline-aws
spec:
  selector:
    app: devops-03-pipeline-aws
    
  ports:
  - port: 8083
    targetPort: 8083

  type: LoadBalancer    